### ISSUE TITLE
Optiscroll prevents scrolling parent regardless of setting

### ISSUE THREAD

**Issue by stereokai** [wilsonfletcher/Optiscroll#18] opened 2016-01-18 18:03 UTC
Optiscroll limits the scrolling to within the scrolled element, and doesn't scroll the entire page when it reaches the edges of the content, regardless of setting.

**Comment by albertogasparin** [comment] 2016-01-19 14:22
Can you provide more information? Like browser, Optiscroll version and possibly an example code?

**Comment by stereokai** [comment] 2016-01-19 15:05
Can I chat with you privately somehow? I can give you a direct link to the project

Thanks!

**Comment by stereokai** [comment] 2016-01-20 11:39
@albertogasparin Latest Optiscroll, happens in Chrome and Firefox, tested on Mac and Windows :)

Also happens in Safari. Doesn't happen in IE11 and Edge.

**Comment by albertogasparin** [comment] 2016-01-21 10:44
I think the issue you are describing is the default browser behaviour if you have nested scrollbars. Sometimes the browser will prevent the parent scroll if it thinks that you still want to scroll the nested child (especially in Firefox).
I've checked in Firefox and Chrome [the demo page](http://wilsonfletcher.github.io/Optiscroll/) with JS turned on and then disabled. The scroll behaviour looks exactly the same to me.
If you are experiencing something different please provide me a way to better understand your issue.

**Comment by stereokai** [comment] 2016-01-21 10:47
Believe me, it's not native browser behavior. I've been dealing with scrolling for a long time now. It didn't happen before I implemented Optiscroll in my project, and doesn't happen with Optiscroll disabled.

I can DM you a direct tunnel to my project and you can look for yourself - should we switch to twitter?

**Comment by albertogasparin** [comment] 2016-01-21 16:59
I'm going to close this as the issue is related on how browsers bubble the scroll event to `body` and `window` (undocumented feature). It appears not being an Optiscroll bug.

**Closed by albertogasparin** 2016-01-21 16:59 UTC
Labels: invalid
